name: Frontend CI/CD Pipeline

on:
  push:
    branches: [main]  # Change to your branch name if needed

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/lms-frontend
  REACT_APP_API_URL: http://${{ secrets.SERVER_IP }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            REACT_APP_API_URL=${{ env.REACT_APP_API_URL }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} '
            echo "Stopping existing frontend container..."
            sudo docker-compose down
            echo "Removing old images..."
            sudo docker system prune -af
            echo "Pulling new frontend image..."
            sudo docker-compose pull frontend
            echo "Starting new frontend container..."
            sudo docker-compose up -d --force-recreate frontend
            echo "Deployment complete!"
          '
